name: Adopte Un Git
description: Parce que Git c'est pas tout le temps facile et qu'il faut apprendre à l'apprivoiser...
meta_description: "Adopte Un Git - Parce que Git c'est pas tout le temps facile et qu'il faut apprendre à l'apprivoiser..."

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: ""
domain_name: 'http://adopteungit.fr'
google_analytics: 'UA-82263007-1'
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
lang: fr-FR

# Details for the RSS feed generator
url:            'http://adopteungit.fr'
author:         'Loïc Giraudel'
author_description: 'Développeur web passionné de nouvelles technologies vivant reclus dans ses montagnes Grenobloises.'